### ISSUE TITLE
LockedDimensions

### ISSUE THREAD

**Issue by brandyyn** [mrdeadlocked/external_wpa_supplicant_8#1]
sorry this is completely unrelated to any of your projects but i saw in a crash report that you had a mod called "LockedDimensions-0.9.2.jar" which has no download anywhere online and the wayback machine is down and was hacked, so if it has a version to download on it, which i also doubt i can't get that right now, is there any chance you still have that mod?

@mrdeadlocked

**Comment by mrdeadlocked** [comment]
nope sorry, but could something l;ke this work https://www.curseforge.com/minecraft/mc-mods/dimension-access-manager

**Comment by brandyyn** [comment]
> nope sorry, but could something l;ke this work https://www.curseforge.com/minecraft/mc-mods/dimension-access-manager

it’s not for 1.7.10 :/

**Comment by mrdeadlocked** [comment]
ah. sorry.
